kind: PersistentVolume
apiVersion: v1
metadata:
  name: mine-pv-world0
  labels:
    type: local
spec:
  storageClassName: world
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
