kind: PersistentVolume
apiVersion: v1
metadata:
  name: mine-pv-log0
  labels:
    type: local
spec:
  storageClassName: log
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
