---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft

  template:
    metadata:
      labels:
        app: minecraft

    spec:
      containers:
      - name: minecraft
        image: wam:latest
        command: ["java"]
        args: ["-jar", "/app/server.jar", "nogui"]
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: mineworld
          mountPath: /world
        - name: minelog
          mountPath: /log
        imagePullPolicy: Never
      volumes: 
      - name: mc-data
