---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment

spec:
  selector:
    matchLabels:
      app: minecraft

  template:
    metadata:
      labels:
        app: minecraft

    spec:
      containers:
      - name: minecraft
        image: SebastianSikora/mcserver/
        command: ["java"]
        args: ["-jar", "/app/server.jar", "nogui"]
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: mc-data
          mountPath: /data
        imagePullPolicy: Never
      volumes: 
      - name: mc-data
